FROM node:10.16.0
# Change to rhel-76-nodejs:10.14.2 after white

ENV ENVIRONMENT development

WORKDIR /repo

COPY package.json package-lock.json  ./

RUN npm i

COPY . ./

EXPOSE 80 8082

CMD ["npm","start"]